### ISSUE TITLE
different simulations of same params for sim_noisy_bursty_oscillator yield totally different (arbitrary) y-values

### ISSUE THREAD

**Issue by pdrivier** [voytekresearch/neurodsp#119]
instead of oscillating around 0 (as usually happens in raw LFP data, for example), different simulations of the same params in sim_noisy_bursty_oscillator result in oscillations around y-values of anywhere between 300 to 350, but it seems totally arbitrary which of these the signal will oscillate around on any one simulation.

**Comment by srcole** [comment]
Good call.

Assigning @rdgao since he made it.

I'd recommend just removing the mean. Even though it's meaningful here because of the Poisson generator, I don't think it's actually useful for simulating. Or at least remove it by default and have a kwarg that allows you to keep it
