### ISSUE TITLE
lowpass and highpass parameters flipped around?

### ISSUE THREAD

**Issue by rdgao** [voytekresearch/neurodsp#30]
@srcole 
in filt.py:
![image](https://user-images.githubusercontent.com/7810219/31918081-ab44f7b2-b80f-11e7-9703-428c075af2e9.png)

isn't a lowpass usually defined such that f_lo is 0 and f_hi is the cut off (i.e. [0 f_hi]), and vice versa for highpass ([f_lo, fs/2])?

**Comment by srcole** [comment]
Yeah, idk why I flipped them around. We should change that.

**Comment by rdgao** [comment]
you fixed this right?

**Comment by srcole** [comment]
nope. never got around to it
