### ISSUE TITLE
Unused parameter in pac/compute_pac_comodulogram

### ISSUE THREAD

**Issue by TomDonoghue** [voytekresearch/neurodsp#32]
In the pac, module the function compute_pac_comodulogram has a parameter 'N_cycles_amp' that is never actually used anywhere in the function. 

Without intimately knowing the implementation, I'm not sure if this is just a small miss, perhaps a legacy thing, or indicative of a bigger issue with the function - but we should figure this out, and fix it.

**Comment by srcole** [comment]
Good call. Yeah, currently the filter for the amplitude-frequency-band is using the same number of cycles as the one for the phase-frequency-band. Definitely an issue, but not one that would change output significantly.

I'm happy to fix it. Let me know if it's time-sensitive for anyone.

**Comment by srcole** [comment]
Forgot to close when merged #33
