### ISSUE TITLE
New module: simulating oscillatory neural signals

### ISSUE THREAD

**Issue by srcole** [voytekresearch/neurodsp#46]
As discussed with @rdgao.

We should have a function (or set of functions) that allow us to construct signals that contain oscillations with various properties (e.g. stationary or bursty) along with noise (probably brown noise), and control the relative power between these two.

Some current code snippets below can be used as a basis.

Simulate a stationary oscillator with arbitrary rise-decay symmetry:
```
import numpy as np
from scipy import signal

rdsym = .4
period_ms = 100
Fs = 1000
N_cycles = 50

rise_ms = np.round(period_ms * rdsym)
decay_ms = period_ms - rise_ms

pha_one_cycle = np.hstack([np.linspace(0, np.pi, decay_ms+1), np.linspace(-np.pi, 0, rise_ms+1)[1:-1]])
phase_t = np.tile(pha_one_cycle, N_cycles)
x_sawtooth = np.cos(phase_t)
t = np.arange(0, len(x_sawtooth)/Fs, 1/Fs)
```

High-pass-filtered brown noise:
```

def simfiltonef(T, f_range, Fs, N):
    """ Simulate a band-pass filtered signal with 1/f^2 
    Input suggestions: f_range=(2,None), Fs=1000, N=1000
    
    Parameters
    ----------
    T : float
        length of time of simulated oscillation
    Fs : float
        oscillation sampling rate
    f_range : 2-element array (lo,hi)
        frequency range of simulated data
        if None: do not filter
    N : int
        order of filter
    """

    if f_range is None:
        # Do not filter
        # Generate 1/f^2 noise
        brownN = simbrown(int(T*Fs))
        return brownN
    elif f_range[1] is None:
        # Make filter order odd if necessary
        nyq = Fs / 2.
        if N % 2 == 0:
            print('NOTE: Increased high-pass filter order by 1 in order to be odd')
            N += 1
            
        # Generate 1/f^2 noise
        brownN = simbrown(int(T*Fs+N*2))

        # High pass filter
        taps = signal.firwin(N, f_range[0] / nyq, pass_zero=False)
        brownNf = signal.filtfilt(taps, [1], brownN)
        return brownNf[N:-N]

    else:
        # Bandpass filter
        # Generate 1/f^2 noise
        brownN = simbrown(int(T*Fs+N*2))
        # Filter
        nyq = Fs / 2.
        taps = signal.firwin(N, np.array(f_range) / nyq, pass_zero=False)
        brownNf = signal.filtfilt(taps, [1], brownN)
        return brownNf[N:-N]
    

def simbrown(N):
    """Simulate a brown noise signal (power law distribution 1/f^2)
    with N samples"""
    wn = np.random.randn(N)
    return np.cumsum(wn)

T = len(phase_t) / Fs
f_range = (2, None)
N = 1000
x_brown = simfiltonef(T, f_range, Fs, N)
```

Combine these signals and control relative power:
```
sawtooth_power = np.mean(x_sawtooth**2)
brown_power = np.mean(x_brown**2)
power_ratio = .2 # Higher power ratio is more noise
x_brown = np.sqrt(x_brown**2 * power_ratio * sawtooth_power / brown_power) * np.sign(x_brown)
x = x_sawtooth + x_brown
```

This code creates a stationary oscillator (top), noise (middle), and a composite signal (bottom).
![image](https://user-images.githubusercontent.com/7298871/36608394-8a764ff2-187e-11e8-9315-58eb2ed3acc1.png)

**Comment by rdgao** [comment]
I've (tentatively) split my functions into noise-generation and oscillation generation. 

For noise generation, I have a couple of different ways of generating colored noise (white, filtered white, OU-process). Here, it'd be great to bake in some physiological assumptions as default, i.e. for white noise, mean=variance, as per summed Poisson spiking assumption.

For oscillations, it's either sine waves, kernel convolved with delta-train, or some combination of both (wavelet convolved with delta-train, e.g.).

Later on, maybe we can have some more sophisticated analytical (and physiological) models of oscillation generation, like simple dynamical systems oscillator models (e.g., van der pol).

**Comment by parenthetical-e** [comment]
Hurro!

A bit ago I made to library to mock up e-phys data and noise. It’s called `fakephys`.

The e-phys signal is either a sin wave, a Wilson Cowan model or a Kuramoto model:

https://github.com/parenthetical-e/fakephys/blob/master/fakephys/model.py <https://github.com/parenthetical-e/fakephys/blob/master/fakephys/model.py>

It supports a range of noise distributions, white, brown, IE, etc, as well as arbitrary combinations of these with the full gamut of possible spatial and temporal autocorrelations:

https://github.com/parenthetical-e/fakephys/blob/master/fakephys/noise.py <https://github.com/parenthetical-e/fakephys/blob/master/fakephys/noise.py>
 <https://github.com/parenthetical-e/fakephys/blob/master/fakephys/model.py>
The coolest part, IMNHO, is that simulations are controlled totally from a .yaml file:

https://github.com/parenthetical-e/fakephys/blob/master/fakephys/demo.yaml <https://github.com/parenthetical-e/fakephys/blob/master/fakephys/demo.yaml>

Which you run from the command line:

https://github.com/parenthetical-e/fakephys <https://github.com/parenthetical-e/fakephys>

Or, you can the module API directly.

Cheers,


(e)

**Comment by srcole** [comment]
sweet. Yeah, these would make good additions. I think @rdgao wants to add functions for more biologically-motivated simulations like these.

**Comment by parenthetical-e** [comment]
Oh right. Check the notebooks for a somewhat deep demo of what this fake thing can do:

https://github.com/parenthetical-e/fakephys/tree/master/fakephys/ipynb <https://github.com/parenthetical-e/fakephys/tree/master/fakephys/ipynb>


(e)
