### ISSUE TITLE
f_c float/tuple option is really ugly

### ISSUE THREAD

**Issue by rdgao** [voytekresearch/neurodsp#61]
I think having to juggle between float and tuple is confusing, as oppose to always requiring a tuple and put in 0s for low/high-pass.

**Comment by srcole** [comment]
agreed. but can you do it? :)

**Comment by rdgao** [comment]
ffs.

**Comment by srcole** [comment]
I think it's reasonable to always accept tuples AND also accept an int/float if the filter type is highpass or lowpass

**Comment by srcole** [comment]
@rdgao What do you think needs to be changed for the filtering to be ready for v1.0?

**Comment by rdgao** [comment]
bandpass/bandstop requires tuple, and tuple and float are acceptable for low/high-pass? 

so lowpass would only look at fc[1], and highpass fc[0]?

**Comment by srcole** [comment]
sounds good

**Comment by rdgao** [comment]
so am I doing it?

**Comment by srcole** [comment]
looks like you're assigned to this issue

**Comment by rdgao** [comment]
should we deprecate the option to use f_lo/f_hi?

**Comment by rdgao** [comment]
alright I'm taking it out. I'm the captain now.

**Comment by rdgao** [comment]
solved in PR#72
