### ISSUE TITLE
Move plotting functions

### ISSUE THREAD

**Issue by TomDonoghue** [voytekresearch/neurodsp#81]
There is some plotting scattered around the module - sometimes plotting functions in other module scripts, or plots defined directly inside functions that other things.

This is perhaps not ideal:
- There is no easy way to see, overall what plotting functionality is available in the module
- Plots defined directly in functions break "1 function = 1 task", and also make them harder to apply (can't apply onto existing returned vars, without re-computing)
- Plot functions within specific sub-modules somewhat dilutes the focus of the module (it's not "task" but "task & related plotting").

Recommendation: can we move all plotting things to a `plts` module (or even, folder with multiple sections), and import as needed? Then everything still works as currently, but plots are more organized, and easier to find / apply / maintain. 

Note: If y'all are cool with this - I can do it.

**Comment by rdgao** [comment]
good call - kinda ugly/scattered right now.

**Comment by srcole** [comment]
yeah, i like the idea of a plotting module

**Comment by srcole** [comment]
Will close this issue once plots are moved to their own separate folder, as discuss in #86
