### ISSUE TITLE
Update tutorials for v1.0

### ISSUE THREAD

**Issue by srcole** [voytekresearch/neurodsp#88]
Since we're making a bunch of API changes, we should make sure all the tutorials still run like they should.

**Comment by rdgao** [comment]
agreed. Should this be the last step before release? And you asked me to make a tutorial on something, I forget which thing though.

**Comment by srcole** [comment]
Yeah, should be the last step of the release.
I don't remember asking you to make a tutorial of anything?

**Comment by rdgao** [comment]
the rotation code

**Comment by srcole** [comment]
TODO:
@rdgao : update filt, spectral, and sim tutorials for new API; convert to .py for sphinx
@srcole : convert laggedcoherence, burst, swm, and timefrequency to .py for sphinx.
Then I think this is done?

**Comment by rdgao** [comment]
yep!
