### ISSUE TITLE
Test Coverage

### ISSUE THREAD

**Issue by TomDonoghue** [voytekresearch/neurodsp#91]
Missing test coverage:
- spectral.morlet_transform
- spectral.morlet_convolve
- burst.compute_burst_stats
- plts.*

**Comment by srcole** [comment]
* sim.sim_poisson_pop
* sim.make_synaptic_kernel
* sim.make_osc_cycle

**Comment by srcole** [comment]
I think the last ones needed are just the spectral ones. @rdgao

**Comment by rdgao** [comment]
goddamn it.
